# SPDX-FileCopyrightText: 2021-2023 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Helsinki"
    groups:
      aws-sdk:
         patterns:
           - "@aws-sdk/*"
      express:
        patterns:
          - "@types/express"
          - "express"
      jest:
        patterns:
          - "@types/jest"
          - "jest*"
          - "ts-jest"
        exclude-patterns:
          - "jest-junit"
      luxon:
        patterns:
          - "@types/luxon"
          - "luxon"
      n-readlines:
        patterns:
          - "@types/n-readlines"
          - "n-readlines"
      supertest:
        patterns:
          - "@types/supertest"
          - "supertest"
