version: "3.7"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-it-db
    container_name: parser-migration-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: migration
