# SPDX-FileCopyrightText: 2021 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: "3.7"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-it-db
    container_name: parser-migration-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: migration
  flyway:
    image: flyway/flyway:10.3.0
    command: -url=jdbc:postgresql://db:5432/migration?preferQueryMode=extendedForPrepared -user=postgres -password=postgres -placeholders.application_user=postgres -placeholders.migration_user=postgres -postgresql.transactional.lock=false migrate
    volumes:
      - ./trevaka/evaka/service/src/main/resources/db/migration:/flyway/sql/evaka
      - ./trevaka/service/src/main/resources/db/data/tampere:/flyway/sql/trevaka
    depends_on:
      - db
    restart: on-failure
  flyway_seutu:
    image: flyway/flyway:10.3.0
    command: -url=jdbc:postgresql://db:5432/seutu?preferQueryMode=extendedForPrepared -user=postgres -password=postgres -placeholders.application_user=postgres -placeholders.migration_user=postgres -postgresql.transactional.lock=false migrate
    volumes:
      - ./trevaka/evaka/service/src/main/resources/db/migration:/flyway/sql/evaka
    depends_on:
      - db
    restart: on-failure
  flyway_vesilahti:
    image: flyway/flyway:10.3.0
    command: -url=jdbc:postgresql://db:5432/vesilahti?preferQueryMode=extendedForPrepared -user=postgres -password=postgres -placeholders.application_user=postgres -placeholders.migration_user=postgres -postgresql.transactional.lock=false migrate
    volumes:
      - ./trevaka/evaka/service/src/main/resources/db/migration:/flyway/sql/evaka
      - ./trevaka/service/src/main/resources/db/data/vesilahti:/flyway/sql/trevaka
    depends_on:
      - db
    restart: on-failure
  flyway_hameenkyro:
    image: flyway/flyway:10.3.0
    command: -url=jdbc:postgresql://db:5432/hameenkyro?preferQueryMode=extendedForPrepared -user=postgres -password=postgres -placeholders.application_user=postgres -placeholders.migration_user=postgres -postgresql.transactional.lock=false migrate
    volumes:
      - ./trevaka/evaka/service/src/main/resources/db/migration:/flyway/sql/evaka
      - ./trevaka/service/src/main/resources/db/data/hameenkyro:/flyway/sql/trevaka
    depends_on:
      - db
    restart: on-failure
  s3:
    image: adobe/s3mock
    ports:
      - "9090:9090"
    environment:
      ROOT: /data
