# SPDX-FileCopyrightText: 2021 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later

include:
  - trevaka/docker-compose.yml
services:
  flyway:
    image: flyway/flyway:10.11.0
    command: -url=jdbc:postgresql://db:5432/evaka_tampere_local?preferQueryMode=extendedForPrepared -user=postgres -password=postgres -placeholders.application_user=postgres -placeholders.migration_user=postgres -postgresql.transactional.lock=false migrate
    volumes:
      - ./trevaka/evaka/service/src/main/resources/db/migration:/flyway/sql/evaka
      - ./trevaka/service/src/main/resources/db/data/tampere:/flyway/sql/trevaka
    depends_on:
      - db
    restart: on-failure
  flyway_seutu:
    image: flyway/flyway:10.11.0
    command: -url=jdbc:postgresql://db:5432/evaka_local?preferQueryMode=extendedForPrepared -user=postgres -password=postgres -placeholders.application_user=postgres -placeholders.migration_user=postgres -postgresql.transactional.lock=false migrate
    volumes:
      - ./trevaka/evaka/service/src/main/resources/db/migration:/flyway/sql/evaka
    depends_on:
      - db
    restart: on-failure
  flyway_vesilahti:
    image: flyway/flyway:10.11.0
    command: -url=jdbc:postgresql://db:5432/evaka_vesilahti_local?preferQueryMode=extendedForPrepared -user=postgres -password=postgres -placeholders.application_user=postgres -placeholders.migration_user=postgres -postgresql.transactional.lock=false migrate
    volumes:
      - ./trevaka/evaka/service/src/main/resources/db/migration:/flyway/sql/evaka
      - ./trevaka/service/src/main/resources/db/data/vesilahti:/flyway/sql/trevaka
    depends_on:
      - db
    restart: on-failure
  flyway_hameenkyro:
    image: flyway/flyway:10.11.0
    command: -url=jdbc:postgresql://db:5432/evaka_hameenkyro_local?preferQueryMode=extendedForPrepared -user=postgres -password=postgres -placeholders.application_user=postgres -placeholders.migration_user=postgres -postgresql.transactional.lock=false migrate
    volumes:
      - ./trevaka/evaka/service/src/main/resources/db/migration:/flyway/sql/evaka
      - ./trevaka/service/src/main/resources/db/data/hameenkyro:/flyway/sql/trevaka
    depends_on:
      - db
    restart: on-failure
