# SPDX-FileCopyrightText: 2021 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later

FROM postgres:13-alpine

COPY init.sql /docker-entrypoint-initdb.d/
CMD ["postgres", "-c", "fsync=off", "-c", "log_statement=all", "-c", "log_destination=stderr"]
