# SPDX-FileCopyrightText: 2021 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: "3.7"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-it-db
    container_name: parser-migration-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: migration
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/migration -user=postgres -password=postgres -placeholders.application_user=postgres -placeholders.migration_user=postgres migrate
    volumes:
      - ./trevaka/evaka/service/src/main/resources/db/migration:/flyway/sql/evaka
      - ./trevaka/service/src/main/resources/db/migration:/flyway/sql/trevaka
    depends_on:
      - db
    restart: on-failure
  s3:
    image: adobe/s3mock
    ports:
      - "9090:9090"
    environment:
      ROOT: /data
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090" ]
      interval: 1s
      timeout: 5s
      retries: 5
