# SPDX-FileCopyrightText: 2021 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later

FROM postgres:14-alpine3.16

COPY init.sql /docker-entrypoint-initdb.d/
CMD ["postgres", "-c", "fsync=off"]
